# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/lele/Downloads/cmake-3.10.1/bin/cmake

# The command to remove a file.
RM = /home/lele/Downloads/cmake-3.10.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lele/Pictures/lass/emp-sh2pc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lele/Pictures/lass/emp-sh2pc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/lele/Downloads/cmake-3.10.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/lele/Downloads/cmake-3.10.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/lele/Downloads/cmake-3.10.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/lele/Downloads/cmake-3.10.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/lele/Downloads/cmake-3.10.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/lele/Downloads/cmake-3.10.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/lele/Downloads/cmake-3.10.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/lele/Downloads/cmake-3.10.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lele/Pictures/lass/emp-sh2pc/CMakeFiles /home/lele/Pictures/lass/emp-sh2pc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lele/Pictures/lass/emp-sh2pc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bit

# Build rule for target.
bit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bit
.PHONY : bit

# fast build rule for target.
bit/fast:
	$(MAKE) -f CMakeFiles/bit.dir/build.make CMakeFiles/bit.dir/build
.PHONY : bit/fast

#=============================================================================
# Target rules for targets named float

# Build rule for target.
float: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 float
.PHONY : float

# fast build rule for target.
float/fast:
	$(MAKE) -f CMakeFiles/float.dir/build.make CMakeFiles/float.dir/build
.PHONY : float/fast

#=============================================================================
# Target rules for targets named circuit_file

# Build rule for target.
circuit_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 circuit_file
.PHONY : circuit_file

# fast build rule for target.
circuit_file/fast:
	$(MAKE) -f CMakeFiles/circuit_file.dir/build.make CMakeFiles/circuit_file.dir/build
.PHONY : circuit_file/fast

#=============================================================================
# Target rules for targets named mult3

# Build rule for target.
mult3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mult3
.PHONY : mult3

# fast build rule for target.
mult3/fast:
	$(MAKE) -f CMakeFiles/mult3.dir/build.make CMakeFiles/mult3.dir/build
.PHONY : mult3/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named kmeans

# Build rule for target.
kmeans: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kmeans
.PHONY : kmeans

# fast build rule for target.
kmeans/fast:
	$(MAKE) -f CMakeFiles/kmeans.dir/build.make CMakeFiles/kmeans.dir/build
.PHONY : kmeans/fast

#=============================================================================
# Target rules for targets named editdist

# Build rule for target.
editdist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 editdist
.PHONY : editdist

# fast build rule for target.
editdist/fast:
	$(MAKE) -f CMakeFiles/editdist.dir/build.make CMakeFiles/editdist.dir/build
.PHONY : editdist/fast

#=============================================================================
# Target rules for targets named innerprod

# Build rule for target.
innerprod: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 innerprod
.PHONY : innerprod

# fast build rule for target.
innerprod/fast:
	$(MAKE) -f CMakeFiles/innerprod.dir/build.make CMakeFiles/innerprod.dir/build
.PHONY : innerprod/fast

#=============================================================================
# Target rules for targets named int

# Build rule for target.
int: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 int
.PHONY : int

# fast build rule for target.
int/fast:
	$(MAKE) -f CMakeFiles/int.dir/build.make CMakeFiles/int.dir/build
.PHONY : int/fast

#=============================================================================
# Target rules for targets named xtabs

# Build rule for target.
xtabs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xtabs
.PHONY : xtabs

# fast build rule for target.
xtabs/fast:
	$(MAKE) -f CMakeFiles/xtabs.dir/build.make CMakeFiles/xtabs.dir/build
.PHONY : xtabs/fast

test/bit.o: test/bit.cpp.o

.PHONY : test/bit.o

# target to build an object file
test/bit.cpp.o:
	$(MAKE) -f CMakeFiles/bit.dir/build.make CMakeFiles/bit.dir/test/bit.cpp.o
.PHONY : test/bit.cpp.o

test/bit.i: test/bit.cpp.i

.PHONY : test/bit.i

# target to preprocess a source file
test/bit.cpp.i:
	$(MAKE) -f CMakeFiles/bit.dir/build.make CMakeFiles/bit.dir/test/bit.cpp.i
.PHONY : test/bit.cpp.i

test/bit.s: test/bit.cpp.s

.PHONY : test/bit.s

# target to generate assembly for a file
test/bit.cpp.s:
	$(MAKE) -f CMakeFiles/bit.dir/build.make CMakeFiles/bit.dir/test/bit.cpp.s
.PHONY : test/bit.cpp.s

test/circuit_file.o: test/circuit_file.cpp.o

.PHONY : test/circuit_file.o

# target to build an object file
test/circuit_file.cpp.o:
	$(MAKE) -f CMakeFiles/circuit_file.dir/build.make CMakeFiles/circuit_file.dir/test/circuit_file.cpp.o
.PHONY : test/circuit_file.cpp.o

test/circuit_file.i: test/circuit_file.cpp.i

.PHONY : test/circuit_file.i

# target to preprocess a source file
test/circuit_file.cpp.i:
	$(MAKE) -f CMakeFiles/circuit_file.dir/build.make CMakeFiles/circuit_file.dir/test/circuit_file.cpp.i
.PHONY : test/circuit_file.cpp.i

test/circuit_file.s: test/circuit_file.cpp.s

.PHONY : test/circuit_file.s

# target to generate assembly for a file
test/circuit_file.cpp.s:
	$(MAKE) -f CMakeFiles/circuit_file.dir/build.make CMakeFiles/circuit_file.dir/test/circuit_file.cpp.s
.PHONY : test/circuit_file.cpp.s

test/editdist.o: test/editdist.cpp.o

.PHONY : test/editdist.o

# target to build an object file
test/editdist.cpp.o:
	$(MAKE) -f CMakeFiles/editdist.dir/build.make CMakeFiles/editdist.dir/test/editdist.cpp.o
.PHONY : test/editdist.cpp.o

test/editdist.i: test/editdist.cpp.i

.PHONY : test/editdist.i

# target to preprocess a source file
test/editdist.cpp.i:
	$(MAKE) -f CMakeFiles/editdist.dir/build.make CMakeFiles/editdist.dir/test/editdist.cpp.i
.PHONY : test/editdist.cpp.i

test/editdist.s: test/editdist.cpp.s

.PHONY : test/editdist.s

# target to generate assembly for a file
test/editdist.cpp.s:
	$(MAKE) -f CMakeFiles/editdist.dir/build.make CMakeFiles/editdist.dir/test/editdist.cpp.s
.PHONY : test/editdist.cpp.s

test/example.o: test/example.cpp.o

.PHONY : test/example.o

# target to build an object file
test/example.cpp.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/test/example.cpp.o
.PHONY : test/example.cpp.o

test/example.i: test/example.cpp.i

.PHONY : test/example.i

# target to preprocess a source file
test/example.cpp.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/test/example.cpp.i
.PHONY : test/example.cpp.i

test/example.s: test/example.cpp.s

.PHONY : test/example.s

# target to generate assembly for a file
test/example.cpp.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/test/example.cpp.s
.PHONY : test/example.cpp.s

test/float.o: test/float.cpp.o

.PHONY : test/float.o

# target to build an object file
test/float.cpp.o:
	$(MAKE) -f CMakeFiles/float.dir/build.make CMakeFiles/float.dir/test/float.cpp.o
.PHONY : test/float.cpp.o

test/float.i: test/float.cpp.i

.PHONY : test/float.i

# target to preprocess a source file
test/float.cpp.i:
	$(MAKE) -f CMakeFiles/float.dir/build.make CMakeFiles/float.dir/test/float.cpp.i
.PHONY : test/float.cpp.i

test/float.s: test/float.cpp.s

.PHONY : test/float.s

# target to generate assembly for a file
test/float.cpp.s:
	$(MAKE) -f CMakeFiles/float.dir/build.make CMakeFiles/float.dir/test/float.cpp.s
.PHONY : test/float.cpp.s

test/innerprod.o: test/innerprod.cpp.o

.PHONY : test/innerprod.o

# target to build an object file
test/innerprod.cpp.o:
	$(MAKE) -f CMakeFiles/innerprod.dir/build.make CMakeFiles/innerprod.dir/test/innerprod.cpp.o
.PHONY : test/innerprod.cpp.o

test/innerprod.i: test/innerprod.cpp.i

.PHONY : test/innerprod.i

# target to preprocess a source file
test/innerprod.cpp.i:
	$(MAKE) -f CMakeFiles/innerprod.dir/build.make CMakeFiles/innerprod.dir/test/innerprod.cpp.i
.PHONY : test/innerprod.cpp.i

test/innerprod.s: test/innerprod.cpp.s

.PHONY : test/innerprod.s

# target to generate assembly for a file
test/innerprod.cpp.s:
	$(MAKE) -f CMakeFiles/innerprod.dir/build.make CMakeFiles/innerprod.dir/test/innerprod.cpp.s
.PHONY : test/innerprod.cpp.s

test/int.o: test/int.cpp.o

.PHONY : test/int.o

# target to build an object file
test/int.cpp.o:
	$(MAKE) -f CMakeFiles/int.dir/build.make CMakeFiles/int.dir/test/int.cpp.o
.PHONY : test/int.cpp.o

test/int.i: test/int.cpp.i

.PHONY : test/int.i

# target to preprocess a source file
test/int.cpp.i:
	$(MAKE) -f CMakeFiles/int.dir/build.make CMakeFiles/int.dir/test/int.cpp.i
.PHONY : test/int.cpp.i

test/int.s: test/int.cpp.s

.PHONY : test/int.s

# target to generate assembly for a file
test/int.cpp.s:
	$(MAKE) -f CMakeFiles/int.dir/build.make CMakeFiles/int.dir/test/int.cpp.s
.PHONY : test/int.cpp.s

test/kmeans.o: test/kmeans.cpp.o

.PHONY : test/kmeans.o

# target to build an object file
test/kmeans.cpp.o:
	$(MAKE) -f CMakeFiles/kmeans.dir/build.make CMakeFiles/kmeans.dir/test/kmeans.cpp.o
.PHONY : test/kmeans.cpp.o

test/kmeans.i: test/kmeans.cpp.i

.PHONY : test/kmeans.i

# target to preprocess a source file
test/kmeans.cpp.i:
	$(MAKE) -f CMakeFiles/kmeans.dir/build.make CMakeFiles/kmeans.dir/test/kmeans.cpp.i
.PHONY : test/kmeans.cpp.i

test/kmeans.s: test/kmeans.cpp.s

.PHONY : test/kmeans.s

# target to generate assembly for a file
test/kmeans.cpp.s:
	$(MAKE) -f CMakeFiles/kmeans.dir/build.make CMakeFiles/kmeans.dir/test/kmeans.cpp.s
.PHONY : test/kmeans.cpp.s

test/mult3.o: test/mult3.cpp.o

.PHONY : test/mult3.o

# target to build an object file
test/mult3.cpp.o:
	$(MAKE) -f CMakeFiles/mult3.dir/build.make CMakeFiles/mult3.dir/test/mult3.cpp.o
.PHONY : test/mult3.cpp.o

test/mult3.i: test/mult3.cpp.i

.PHONY : test/mult3.i

# target to preprocess a source file
test/mult3.cpp.i:
	$(MAKE) -f CMakeFiles/mult3.dir/build.make CMakeFiles/mult3.dir/test/mult3.cpp.i
.PHONY : test/mult3.cpp.i

test/mult3.s: test/mult3.cpp.s

.PHONY : test/mult3.s

# target to generate assembly for a file
test/mult3.cpp.s:
	$(MAKE) -f CMakeFiles/mult3.dir/build.make CMakeFiles/mult3.dir/test/mult3.cpp.s
.PHONY : test/mult3.cpp.s

test/xtabs.o: test/xtabs.cpp.o

.PHONY : test/xtabs.o

# target to build an object file
test/xtabs.cpp.o:
	$(MAKE) -f CMakeFiles/xtabs.dir/build.make CMakeFiles/xtabs.dir/test/xtabs.cpp.o
.PHONY : test/xtabs.cpp.o

test/xtabs.i: test/xtabs.cpp.i

.PHONY : test/xtabs.i

# target to preprocess a source file
test/xtabs.cpp.i:
	$(MAKE) -f CMakeFiles/xtabs.dir/build.make CMakeFiles/xtabs.dir/test/xtabs.cpp.i
.PHONY : test/xtabs.cpp.i

test/xtabs.s: test/xtabs.cpp.s

.PHONY : test/xtabs.s

# target to generate assembly for a file
test/xtabs.cpp.s:
	$(MAKE) -f CMakeFiles/xtabs.dir/build.make CMakeFiles/xtabs.dir/test/xtabs.cpp.s
.PHONY : test/xtabs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bit"
	@echo "... float"
	@echo "... circuit_file"
	@echo "... mult3"
	@echo "... example"
	@echo "... install/local"
	@echo "... kmeans"
	@echo "... editdist"
	@echo "... innerprod"
	@echo "... int"
	@echo "... xtabs"
	@echo "... test/bit.o"
	@echo "... test/bit.i"
	@echo "... test/bit.s"
	@echo "... test/circuit_file.o"
	@echo "... test/circuit_file.i"
	@echo "... test/circuit_file.s"
	@echo "... test/editdist.o"
	@echo "... test/editdist.i"
	@echo "... test/editdist.s"
	@echo "... test/example.o"
	@echo "... test/example.i"
	@echo "... test/example.s"
	@echo "... test/float.o"
	@echo "... test/float.i"
	@echo "... test/float.s"
	@echo "... test/innerprod.o"
	@echo "... test/innerprod.i"
	@echo "... test/innerprod.s"
	@echo "... test/int.o"
	@echo "... test/int.i"
	@echo "... test/int.s"
	@echo "... test/kmeans.o"
	@echo "... test/kmeans.i"
	@echo "... test/kmeans.s"
	@echo "... test/mult3.o"
	@echo "... test/mult3.i"
	@echo "... test/mult3.s"
	@echo "... test/xtabs.o"
	@echo "... test/xtabs.i"
	@echo "... test/xtabs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

